### ISSUE TITLE
Couleur du graph

### ISSUE THREAD

**Issue by ftoromanoff** [ign-packo/PackO#104]
La méthode actuelle de choix de couleur est complètement aléatoire, définie par un triplet RGB non déjà choisit.
Cela amène parfois à des couleurs voisines très proches lors de la visualisation.

Pour résoudre cela, doit on :
- revoir l'algorithme de choix de couleur (lors de la création du cache) ?
- permettre à l'utilisation de modifier une couleur spécifiquement ?
- autre ?

**Comment by amrosu** [comment]
Demande interne 1911 : avoir des contours (=limites des OPI) dans le graphe à la place des couleurs.

itowns est en train d'évoluer en prenant en compte cette demande

La demande sur les contours pourrait évoluer avec l'ajout d'options utilisateur comme : 
- pouvoir modifier l'épaisseur du trait (fonctionnalité normalement prévue dans l'évolution en cours sur itowns sur la mise en place des contours)
- pouvoir modifier la couleur du contour (voir en fonction des évolutions itowns)
