### ISSUE TITLE
Affichage des contours du graphe plutôt que la teinte

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#133]
# Motivation
Dans le vue itowns, les utilisateurs souhaitent afficher les contours du graphe plutôt que la teinte: cela règle le problème des teinte trop proche et cela perturbe moins l'analyse de la qualité du résultat.

# Démarche
On ne change rien sur la création du cache, ça sera entièrement géré au niveau de l'affichage dans iTowns. Cette possibilité a déjà été ajouté sur le master d'iTowns (https://github.com/iTowns/itowns/pull/1656) et sera prise en charge dans la prochaine release (2.33).

**Comment by amrosu** [comment]
Ce ticket est en lien avec #104

**Comment by amrosu** [comment]
La demande sur les contours pourrait évoluer avec l'ajout d'options utilisateur comme :  pouvoir modifier l'épaisseur du trait (fonctionnalité normalement prévue dans l'évolution en cours sur itowns sur la mise en place des contours)
