### ISSUE TITLE
gérer les ports utilisés

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#14]
Pour éviter des conflits entre APIs et donner la possibilité de faire fonctionner plusieurs en même temps, il faudrait donner la possibilité de modifier les ports à utiliser  - rendre paramétrable leur valeur, avec valeur standard comme valeur par défaut

**Comment by gmaillet** [comment]
Je propose de faire une PR pour la gestion des options dans serveur.js:

- ajouter une option pour choisir le port
- ajouter une option pour choisir le dossier cache (à la place de l'option cache_test)
