### ISSUE TITLE
Ré-échantillonnage dans moniteur

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#149]
## Motivation
Pour la visualisation, il peut être bien utile d'avoir des niveaux de zoom/dezoom obtenus par ré-échantillonnage des niveaux calculés.

Actuellement, (suite aux #134, #142), dans le moniteur (itowns), on peut afficher un niveau sur-échantillonné (zoom+1) par rapport au niveau max calculé du cache, mais aucun sous-échantillonnage possible par rapport au niveau min calculé.

## Démarche
Rendre disponible aussi la possibilité de sous-échantillonnage, au moins zoom-1, pour permettre une vue d'ensemble du chantier ou au moins une région plus grande du chantier.

**Comment by ftoromanoff** [comment]
Pour le sous-échantillonnage, un ticket a été ouvert dans itowns. Il semblerait qu'il y ai une mauvaise gestion du minResolution dans les paramètres de la camera orthographique.

**Comment by amrosu** [comment]
Des corrections sont en cours dans la PR #158

**Comment by amrosu** [comment]
La PR #158 a été remplacée par PR #162, les corrections seront donc apportées par PR #162
