### ISSUE TITLE
Couche avec alertes / annotations des défauts 

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#160]
Ajouter une couche pour des alertes (annotations utilisateur avec les défauts trouvés sur le chantier) avec un dictionnaire de type d'alertes / annotations.

Formulation de la demande:
- Afin de pouvoir suivre une liste d’objets à contrôler, il doit être possible de parcourir une liste d’objets géo-référencés (liste de ponctuels), en renseignant au fur et à mesure un attribut signalant l’état du traitement.
- Au cours du contrôle et de la correction de la mosaïque, il doit être possible de saisir des objets (ponctuels ou surfaciques, avec une liste prédéfinie et un champ texte libre comme attributs) marquant des points d’intérêt (par exemple des défauts non corrigés ou à corriger ultérieurement par d’autres moyens que le mosaïquage).
- Ceux-ci seront exportables dans un format vecteur (shp ou gpkg).

**Comment by ftoromanoff** [comment]
1ère demande :
 =>PR #242 
- cette demande a même été élargie au parcours d'objets géoréférencés de type polygone et multilignes.

2ème demande :
- Saisie d'objets ponctuels avec un champ texte libre => PR #251 
Reste à développer :
- Saisie d'objets surfaciques
- Export
