### ISSUE TITLE
Basculement entre les affichages RVB/IR/IRC

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#190]

**Comment by nlenglet-ign** [comment]
Images de test 4 canaux obtenus par cette méthode :
- séparer les 3 canaux du rgb via gdalbuildvrt : `gdalbuildvrt -b 1/2/3 red/green/blue.vrt opi.tif`
- créer un vrt contenant les 4 canaux que l'on souhaite dans l'image finale : `gdalbuildvrt -separate rgbi.vrt red.vrt green.vrt blue.vrt ir.vrt`
- conversion de ce vrt vers le format Tiff via gdal_translate : `gdal_translate -of GTiff -co "TILED=YES" rgbi.vrt rgbi.tif`

**Comment by nlenglet-ign** [comment]
Il faut séparer la gestion du découpage graph et ortho (nombre de canaux fixe pour le graph (3))

**Comment by nlenglet-ign** [comment]
Obsolète : on traite la gestion des 4 canaux dans la PR #250
