### ISSUE TITLE
gérer le GetFeatureInfo hors de la zone

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#20]
Pour le moment il n'y a pas de test avant le Jimp.read

**Comment by ftoromanoff** [comment]
J'ai rajouté un test sur la branche CreateCache

**Comment by ftoromanoff** [comment]
erreur 400 accompagné de la réponse suivante :
{
  "status": "out of bounds",
  "errors": [
    {
      "localisation": "GetFeatureInfo",
      "msg": "out of bounds"
    }
  ]
}
