### ISSUE TITLE
Gestion des données OPI en conformité avec WMTS

### ISSUE THREAD

**Issue by ftoromanoff** [ign-packo/PackO#22]
itowns envoie des requêtes GetTile avec LAYER = opi mais aussi avec LAYER=${nom_de_l_OPI}. Ce qui impliquerait que la couche 'opi' et chaque OPI soit déclarées dans le GetCapabilities.

Je propose d'essayer de mettre la couche opi en multi-dimension avec 1 dimension par OPI, pour n'avoir qu'une couche a déclarer.

**Comment by gmaillet** [comment]
C'est ce que j'avais prévu au départ mais je pense que nous ne pourrons pas être totalement conforme au standard parce qu'il faudrait déclarer toutes les OPI dans le GetCapabilities et j'ai peur que cela soit trop lourd (possiblement des dizaines de milliers d'OPI).
En tout cas, ce n'est absolument pas prioritaire on a des trucs plus urgent que la conformité au standard.

**Comment by ftoromanoff** [comment]
prise en compte dans la branche OpiDimension
