### ISSUE TITLE
Incohérence entre le moniteur itowns et la BD sur les noms des branches

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#227]
Incohérence liée à la manière différente dont les caractères spéciaux sont traités dans le moniteur itowns et dans la bd :
* dans la BD, on accepte tous les caractères spéciaux sans aucun traitement -> les noms des branches sont gardés comme tels
* dans itowns, il y a des traitements :  exemples :  
     - "<" comme premier caractère du nom fait que celui-ci "s'évapore" (on a un champ vide dans la partie nom de branche) 
     -  espace(s) avant le nom - enlevé(s) du nom affiché 
En regardant donc la liste de noms de branches dans itowns on a l'impression que l'unicité des noms de branches n'est pas respectée (et peut créer facilement des confusions dans le travail)

**Comment by nlenglet-ign** [comment]
Pour les noms de branche, limiter les caractères valides à : 
- caractères alphanumériques non accentués
- '-' et '_'
