### ISSUE TITLE
Gestion des niveaux liés aux 2ème COG - échelles < 1/16

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#233]
Lié aux tickets internes n° 2012, 2013, 2017 + 2022

# Motivation : 
Gérer plus finement la visualisation et l'application de patchs sur le graphe aux petites échelles (< 1:16) -> ces échelles correspondent aux niveaux du 2ème COG

# Demandes pour les échelles <1/16 : 
- [x]  retirer l'affichage du graphe (couches Contour et Graph) pour ne pas induire les utilisateurs en erreur - fait dans PR #235
- [x]  ajouter une information pour l'utilisateur du type "graphe non visible" à côté de la valeur de l'échelle peut-être -fait dans PR #236 
- [ ] ne pas permettre de saisir de polygone à des échelles <1/16 / ne pas afficher le 2ème COG si on est en mode saisie ou OPI sélectionnée ?
- [ ] laisser les vecteurs importés dans l'état dans lequel ils se trouvent auparavant (visibles ou cachés), ce sont des données ajoutées par l'utilisateur qui doivent rester sous son contrôle en ce qui concerne l'affichage ou non

**Comment by gmaillet** [comment]
PR #235 pour la première partie (retirer l'affichage du graphe (couches Contour et Graph) pour ne pas induire les utilisateurs en erreur)

**Comment by gmaillet** [comment]
PR #236 pour la deuxième partie (ajouter une information pour l'utilisateur du type "graphe non visible" à côté de la valeur de l'échelle peut-être). Le rendu n'est pas très beau, mais c'est un premier essai.

**Comment by amrosu** [comment]
J'ai ajouté dans la liste de tâches la demande sur la gestion des vecteurs à des échelles < 1/16 (ticket interne 2022)

**Comment by ftoromanoff** [comment]
Les patches par contre doivent suivre la même règle que le graph ou que les autres couches vecteur ?

**Comment by amrosu** [comment]
Concernant la demande de ne pas pouvoir faire des saisies à des échelle < 1/16  (3ème tâche de ce ticket) : on ne voit plus les saisies et on n'a plus le droit de saisir de polygone à des échelles < 1/16 (à partir de master 079797e), mais les actions undo/redo sont toujours possibles à toutes les échelles, l'utilisateur peut donc agir sur les saisies à des niveaux de zoom sur lesquelles il ne voit pas l'effet de son action

tests faits sur master 079797e et sa dernière version à ce jour 07a902e

**Comment by ftoromanoff** [comment]
Effectivement, je n'avais pas pris en compte le Undo et le Redo. C'est chose faite sur la PR #269
