### ISSUE TITLE
pb avec Select Opi après chargement d'un vecteur

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#246]
Dans itowns, je vois qu'après avoir chargé un vecteur annexe, si je fais *Select* pour sélectionner une OPI, j'ai cette erreur :
![image](https://user-images.githubusercontent.com/24602370/142610079-636b6094-2a29-48e9-9107-2ecfe8f1ba84.png)

Tests faits sur la dernière version du master (906bc74e1) et sur la dernière version livrée (29480f0)

**Comment by ftoromanoff** [comment]
J'ai été confronté a cette même erreur sur ma branche de gestion des alertes pour d'autre situation. Elle ne devrait plus apparaitre.
A voir si il y a besoin de transférer seulement ce correctif avant le merge avec les alertes

**Comment by amrosu** [comment]
Oui, il faudrait faire une petite PR avec la correction dès qu'elle est disponible, merci

**Comment by amrosu** [comment]
Le problème semble bien corrigé - dernière version testée master 00dbee62
