### ISSUE TITLE
Pb lorsqu'on ajoute une couche vecteur pendant qu'on réalise l'on traite des alertes

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#258]
Lorsqu'on a choisi une couche d'alerte et qu'on glisse un nouveau fichier vecteur: la couche utilisée pour les alertes est désélectionnée, mais l'affichage n'est pas n'est pas correctement rafraichi.
Par exemple, le point courant reste jaunes, les points validés sont verts et les non validé sont rouges.

**Comment by ftoromanoff** [comment]
Résolu dans la PR #260
