### ISSUE TITLE
désafficher les alertes

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#262]
Correspond au ticket interne 2025 (lien probable avec #258)

Il est nécessaire de pouvoir désélectionner/désafficher les alertes :
 - Ne plus avoir de fichier d'alertes sélectionné
- Ne pas avoir les alertes du fichier sélectionné affichées en permanence : pouvoir les cacher comme les autres vecteurs
Il faut pouvoir rendre invisibles les alertes (actuellement les symboles persistent) et pouvoir garder le fichier en référence sans avoir d'entité sélectionnée.

**Comment by gmaillet** [comment]
à faire: ajouter un choix "None" (afficher comme "-") dans le menu déroulant et lier l'affichage de la couche "surligné" avec celui de la couche vecteur correspondante.

**Comment by ftoromanoff** [comment]
Résolus dans la PR #260
