### ISSUE TITLE
navigation dans couche d'alerte

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#263]
Correspond au ticket interne 2024 et en lien avec #257 :

Afin de naviguer beaucoup plus clairement dans les alertes, il faut plusieurs choses :
- [x] avoir l'id de l'entité courante ( idx / total )
- [x] pouvoir renseigner un id particulier pour se déplacer directement sur cette entité (idx éditable)
- [x] avoir un attribut 'vu' et un attribut 'validé' au lieu de 'checked'
       -> unchecked, checked et validated
- [x] pouvoir agir sur ces 2 attributs manuellement si besoin ('validé' évidemment, mais 'vu' qui passe automatiquement de faux à vrai doit pouvoir revenir à faux si besoin)
- [x] l'avancement noté dans la case devra donc se faire via l'attribut 'vu'. La proportion de 'validé' sera un avantage afin de connaitre la proportion de modifications effectuées sur le chantier.
       -> nb checked/nb total (nb validated)

C'est nécessaire pour pouvoir
- avancer sans s'arrêter à chaque situation qui pose question et sera revue à chaque redémarrage du contrôle
- revenir rapidement sur les situations à question en présence d'un support
- pouvoir avoir un avancement plus précis (validé (ie vu et modifié), vu, pas vu)

**Comment by ftoromanoff** [comment]
1) l'id actuel est un id propre a notre base de donnée. Il n'y a pas d'enregistrement en base de l'id initial..
2) Actuellement on peut cliquer sur une entité pour y aller directement

**Comment by ftoromanoff** [comment]
Les différentes demandes sont résolues dans la PR #268
