### ISSUE TITLE
gérer l'intégrité du cache

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#27]
Si on travaille sur un dossier cache existant, il faut assurer l'intégrité de sa mise à jour - le plus simple serait de le purger et le recréer au lancement du createCache, car sinon
* si on a un problème sur une tuile (à cause d'un bug par exemple), la tuile n'est pas mise à jour et donc la correction du bug pas prise en compte
* si il y a eu une modification dans une ou plusieurs OPI ou graphe et si leurs noms restent les mêmes, la modification n'est pas prise en compte dans le cache

**Comment by ftoromanoff** [comment]
Pour moi createCache est une opération manuelle effectuée par un opérateur qui sait ce qu'il fait.
Du coup, un message d'erreur bloquant peut suffire : "attention: l'OPI xxxxx déjà existante dans le cache"
- Soit c'est un oubli de l'operateur qui relance son calcul de cache en enlevant l'OPI en double
- Soit c'est parce que l'OPI précédente était buggée, et dans ce cas l'opérateur doit recalculer un cache complet après suppression manuelle

**Comment by ftoromanoff** [comment]
Normalement c'est réglé sur la branche createCache
