### ISSUE TITLE
Bug : clear en mode production

### ISSUE THREAD

**Issue by nlenglet-ign** [ign-packo/PackO#335]
Le bouton **clear** apparaît lorsque l'on est en mode production (alors qu'il n'est censé apparaître qu'en mode dev), quelque soit la branche (y compris orig) et si on clique sur ce bouton, l'erreur suivante apparaît : 
![erreur_clear](https://user-images.githubusercontent.com/58478624/179924103-4172db19-2ed0-4658-a34f-3ee62b78c638.PNG)

Branch : master
Commits : [2184042](https://github.com/ign-packo/PackO/commit/2184042aa038c7813714be4bf7e1f5fb836c780a) & [ca19569](https://github.com/ign-packo/PackO/commit/ca19569942849b0bc20e6cc9bea6190975ac536d) & [a386a38](https://github.com/ign-packo/PackO/commit/a386a38ac4126cd9b3b534f66c4a71d18a6f7d98)

**Comment by ftoromanoff** [comment]
Effectivement, le bouton 'clear' doit être invisible par défaut, contrairement aux autres.

**Comment by ftoromanoff** [comment]
Je corrige sur ReworkMenu #325
