### ISSUE TITLE
saisie en dehors de la zone de l'OPI sélectionnée

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#34]
Il faut gérer le cas d'une saisie en dehors de la zone d'intérêt (zone de l'OPI sélectionnée) : il faudrait mettre un message du type "Saisie hors zone" et la saisie ne doit pas avoir d'effet (ce qui n'est pas le cas actuellement et la saisie de ce type crée un "trou")

**Comment by ftoromanoff** [comment]
Dans la version 'undo_redo_2' une saisie de polygone qui dépasse de l'emprise, ce change rien au niveau de l'ortho et du graph et renvoie un message dans itowns
