### ISSUE TITLE
saisie en bord de l'OPI

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#35]
Il faut gérer les saisies en bord de l'OPI sélectionnée et qui peuvent sortir de la zone de l'OPI.

Options :  

1.  ne pas prendre en compte cette saisie - ce qui est fait actuellement, mais cela n'est pas optimal car un travail de saisie (qui peut être conséquent), s'il dépasse d'un pixel la zone, est mis à la poubelle

2.  prendre en compte seulement la partie de la saisie qui est contenue dans la zone et exclure (découper) automatiquement ce qui dépasse - nettement mieux et sympa pour l'utilisateur

**Comment by ftoromanoff** [comment]
le problème n'est pas en bordure d'une OPI mais en bordure de l'emprise de la zone

**Comment by amrosu** [comment]
Le problème d'une saisie en bord de l'emprise du projet est un problème légèrement différent - il faudrait faire un autre ticket
Ce ticket s'occupe de l'emprise de l'OPI sélectionnée uniquement

**Comment by ftoromanoff** [comment]
Mais dans ce cas il n'y a pas réellement de problème paracerque ca voudrait dire que l'operateur choisit consciemment la partie noire de l'OPI, ce qui n'a, je pense, pas de sens....

**Comment by amrosu** [comment]
Comme je l'expliquais plus haut, on peut faire une saisie qui est majoritairement dans l'OPI, mais avec un ou plusieurs pixels en dehors de l'OPI, je ne parle pas de partie avec info ou de la partie avec uniquement des pixels noirs

**Comment by amrosu** [comment]
Et actuellement, dans la branche undo_redo_2, ce cas est géré avec la solution 1 : saisie pas prise en compte + message qui indique que la saisie est en dehors des limites de l'OPI : même si, je le répète, on a une saisie qui n'est pas entièrement en dehors de l'emprise de l'OPI, mais qui a une partie dedans et une partie en dehors les limites de l'OPI
La solution 2, qui me parait mieux, est de ne pas éliminer cette saisie, mais la garder en découpant la partie qui est en dehors de l'OPI

**Comment by ftoromanoff** [comment]
Mais dans ce cas tu te retrouves avec pleins de pixels noirs, donc saisie inutile...

**Comment by gmaillet** [comment]
Je n'ai pas testé, mais je pense que ce qui se passe c'est que lors de l'application du patch (sur le serveur) il y a une erreur sur les tuiles où l'on applique une OPI qui n'est pas présente dans la tuile. Dans ce cas, j'imagine que le serveur annule tout et renvoie un code d'erreur (à vérifier).
Ce que l'on peut envisager, c'est de ne pas considérer cela en erreur et d'avoir un patch qui s'arrête aux limites des tuiles contenant l'OPI utilisé (c'est la solution la plus simple au niveau du code)?

**Comment by amrosu** [comment]
effectivement, c'est le cas avec le type d'OPI que nous avons actuellement qui ont le cercle définissant la zone utile
Et dans tous les cas, les saisies en limites de zone d'OPI, même si on n'avait pas de pixels noirs, ne sont pas terribles vu la qualité de l'OPI sur les bords et qu'il faut les éviter.
Donc ce ticket n'a pas vraiment d'utilité et je vais donc le fermer

**Comment by amrosu** [comment]
Désolée, j'ai fermé le ticket avant de voir le message de Greg. Je vais le laisser ouvert pour la discussion
