### ISSUE TITLE
Bug API si chemin contient un 'x'

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#353]
Actuellement, dans le cas du travail sur un cache IR ou RVBIR, si le chemin (url) vers la tuile/dalle contient un 'x' il est remplacé par '_ix', avec pour résultat un chemin qui n'existe pas et donc impossible de récupérer la tuile (image noire à la place).

**Comment by nlenglet-ign** [comment]
Il me semble que ce bug était également présent lors de la création de cache, un fix avait été fait pour gérer le cas dans le path, par contre si on a un 'x' supplémentaire dans le filename, je crois que c'est toujours le cas.

**Comment by amrosu** [comment]
Le 'filename' est normalisé, avec un seul 'x' minuscule possible. 
J'ai l'impression que le seul cas où on peut avoir un 'x' supplémentaire c'est  'X' (majuscule) dans le nom de la dalle générée et cela peut éventuellement poser problème sous un OS non sensible à la case par défaut, comme Windows, mais cela peut être configuré
