### ISSUE TITLE
Raccourci 'v' non fonctionnel

### ISSUE THREAD

**Issue by nlenglet-ign** [ign-packo/PackO#355]
Le raccourci 'v' permettant de déplier/plier le menu contenant les extra layers dans le monitor ne fonctionne plus.

**Comment by nlenglet-ign** [comment]
Mauvaise manip, cela fonctionne.

**Comment by amrosu** [comment]
Petite précision : ce raccourci '-v' sert à masquer/afficher tous les vecteurs et non pas à "déplier/plier le menu..."
