### ISSUE TITLE
Bug validation alertes

### ISSUE THREAD

**Issue by nlenglet-ign** [ign-packo/PackO#368]
Bug constaté sur master, commit 365e14c0a62922fff112b451bf73f1cd6fc13761

Etapes à reproduire pour faire apparaître le bug :
- créer une branche sur un cache quelconque
- saisir une alerte et la valider (état 1), puis la supprimer
- saisir une nouvelle alerte (impossible de la sélectionner en faisant défiler avec les flèches ou en cliquant dessus). Pour pouvoir la sélectionner, il faut appuyer sur 'c' (raccourci pour valider une alerte), on se retrouver alors dans l'état 2, avec -1 alerte validée.
- quand on valide effectivement cette alerte, on se retrouve alors avec 0 alerte validée (état 3)

(1) ![bug_alertes_1](https://user-images.githubusercontent.com/58478624/203317868-8c652492-2b2e-4e7d-a647-dd9943b3afeb.PNG)
(2) ![bug_alertes_2](https://user-images.githubusercontent.com/58478624/203316381-ddc5e973-d829-454f-9285-488bc4f4877a.PNG)
(3) ![bug_alertes_3](https://user-images.githubusercontent.com/58478624/203316397-08d3d5a3-eafc-4b04-9e13-0f0edb8a8e2e.PNG)

**Comment by ftoromanoff** [comment]
J'ai l'impression que ce n'est pas lié au fait de valider ou non l'alerte mais juste a cause de la suppression d'une alerte unique.

**Comment by amrosu** [comment]
Ce bug semble avoir été introduit en septembre avec la branche ClassAlert (PR #324) mise dans master -> v1.4.4 (7990db38)
Il y a un problème sur la gestion de la validation : la nouvelle alerte, ajoutée après la suppression (état 2) est validée par défaut avec Progress à 0/1 (0 validés)
