### ISSUE TITLE
option réaffichage des saisies effectuées

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#38]
Dans le menu, créer une couche avec les polygones des saisies effectuées et ajouter une option de visualisation

**Comment by gmaillet** [comment]
Dans un premier temps on peut 
1. ajouter une route sur l'API pour récupérer un GeoJson des saisies (c'est déjà plus ou moins le fichier activePatchs.json)
2. importer ce fichier dans iTowns comme une couche, est assurer le refresh dès qu'il y a une modification
Pour bien faire (dans une deuxième temps): il faudrait avoir un flux vecteur tuilé pour qu'iTowns ne soit pas obligé de tout recharger à chaque fois. On pourra s'inspirer de la gestion ROK4 du vecteur tuilé.

**Comment by amrosu** [comment]
en lien avec #144
