### ISSUE TITLE
Pouvoir pousser les OPI via l'API

### ISSUE THREAD

**Issue by ign-packo** [ign-packo/PackO#4]
- pouvoir ajouter les OPI (avec leur image de qualité)
- pouvoir faire un mosaiquage basique (prendre la qualité max)
- pouvoir faire un mosaiquage optimisé (adapter le code Mosar)
- vérifier les performances sur des gros chantiers

**Comment by gmaillet** [comment]
Discussion du 8/10/2020:
Comment gérer l'ajout de 10000 OPI alors qu'il faut actuellement plusieurs minutes par OPI?
Réponse: ce n'est pas fait par le serveur (il ne sera pas assez puissant) et il faut pouvoir paralléliser.

1. Si on veut pouvoir utiliser plusieurs machines, il faut faire une GPAO, dans le contexte du SIA, il y aura sans doute de gros serveurs: donc on peut commencer par paralléliser sur une machine à l'aide d'un script createCache multithread (plus simple qu'une GPAO).

2. Pour éviter les conflits lors de l'ajout OPI par OPI on peut créer les tuiles d'OPI mais ne faire l'ortho/graph qu'une fois que toutes les OPI sont ajoutées. Cela évite aussi de refaire trop de fois l'ortho et le graph.

3. une fois que toutes les OPI sont ajoutées, on peut paralléliser par tuile pour calculer graph/ortho sans risque de conflit
