### ISSUE TITLE
affichage échelle dans iTowns

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#43]
Avoir une échelle correcte

Problèmes actuels : 

-  vérifié par rapport au Géoportail - j'obtiens des différences non négligeables (un exemple dans captures d'écran plus bas)
![Capture d’écran 2020-10-26 à 16 45 35](https://user-images.githubusercontent.com/24602370/97197534-0d4f9600-17ae-11eb-8232-a5e3e948b374.png)
![Capture d’écran 2020-10-26 à 17 07 17](https://user-images.githubusercontent.com/24602370/97197561-150f3a80-17ae-11eb-8ee9-5858b8675c28.png)

- en zoomant et dézoomant, j'ai des valeurs aberrantes pour l'échelle : je peux passer de 20 km à 58857.39 km en un coup de dezoom ou de 0.14 cm à 5904.93 km en un coup de zoom et parfois il n'arrive plus à se retrouver, il reste bloqué sur la valeur aberrante et mes zoom-dezoom restent sans effet sur l'affichage

- j'ai l'impression aussi qu'il n'y pas vraiment de limites dans les zoom ou dezoom, il serait bien d'en ajouter

**Comment by gmaillet** [comment]
Prévu dans la release 2.28 d'iTowns

**Comment by amrosu** [comment]
à tester après merge #79 dans master

**Comment by ftoromanoff** [comment]
Fait dans la PR #101
