### ISSUE TITLE
Script create_qgis_view: erreur possible dans l'id de la branche

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#435]
Dans le script create_qgis_view.py il y a une erreur possible sur la récupération de l'Id de la branche créée.
En effet, on récupère la liste de toutes les branches et on prend la première qui porte le nom choisi par l'utilisateur, comme l'unicité du nom des branches n'est garanti que pour un cache donné, on peut récupéré l'Id d'une branche plus ancienne sur un autre cache qui porte le même nom.
A corriger: 
- soit en ajoutant l'Id du cache dans la requête de récupération de la liste des branches
- soit en récupérant l'Id de la branche dans la réponse à la requête de création de la branche.

**Comment by amrosu** [comment]
J'utilise bien l'id du cache dans la requête du get pour récupérer la liste des branches, tout comme pour pousser la nouvelle branche :
```
# ---------- create new branch on cache ----------
req_post_branch = ARG.url + '/branch?name=' + branch_name + \
           '&idCache=' + str(ARG.cache_id)
resp_post_branch = check_get_post(req_post_branch, is_get=False)
# get branch id
resp_get_branches = check_get_post(ARG.url + '/branches' +
                                   '?idCache=' + str(ARG.cache_id), is_get=True)
list_all_branches = response2pyobj(resp_get_branches)
branch = next((b for b in list_all_branches if b['name'] == branch_name))
branch_id = branch['id']
print(f"Branch '{branch_name}' created (idBranch={branch_id}) on cache '{cache['name']}'")
```

**Comment by amrosu** [comment]
Je ferme ce ticket car il a été fait sur une version obsolète. J'avais détecté et corrigé le problème il y a plus d'un an.
