### ISSUE TITLE
saisie de coordonnées

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#44]
Donner la possibilité de saisir de coordonnées et centrer l'affichage sur ces coordonnées.

Il ne faut pas rendre l'onglet "coord" éditable par défaut (pour évider des mauvaises manipulations), mais l'ajouter comme option

**Comment by ftoromanoff** [comment]
Je me suis inspiré de ce qui est fait sous QGIS :
la case de coordonnées est éditable est n'est prise en compte qu'après un 'enter'
