### ISSUE TITLE
gérer l'effet d'un clic long de déplacement

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#46]
A voir comment gérer le clic long lors du select ou de la création de polygone : actuellement, un clic long de déplacement est considéré comme un clic dans l'OPI, alors qu'il devrait permettre uniquement le déplacement

**Comment by gmaillet** [comment]
à traiter avec #50

**Comment by ftoromanoff** [comment]
PR #103 :
un clique molette permet le déplacement de la carte sans prise en compte du clique (contrairement a un clique long gauche)
