### ISSUE TITLE
gérer deux select à la suite

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#47]
Le comportement actuel : si on clique sur select après avoir déjà une OPI sélectionnée, le champ "cliche" est vidé et dans le champ "message" contient "choisir un cliche", mais l'OPI sélectionnée auparavant reste mise en évidence
Ce qu'on faudrait faire si on a une OPI et on refait select : mettre dans message "choisir un nouveau cliché" + laisser l'OPI sélectionnée auparavant active + le champ "cliche" rempli avec le nom de cette OPI et le modifier uniquement après avoir cliquer sur une nouvelle OPI

**Comment by ftoromanoff** [comment]
voir branche OPIselect_2
