### ISSUE TITLE
travailler sur l'IHM iTowns

### ISSUE THREAD

**Issue by ign-packo** [ign-packo/PackO#5]
- étudier la possibilité d'avoir plusieurs vues (pas urgent)
- avoir des modes de saisie plus ergonomiques
- pouvoir ajouter d'autres sources (vecteur ou raster) (pas urgent)

- ~~afficher les coordonnées du point cliqué ou survolé par la souris (urgent)~~

- afficher l'échelle (urgent) - j'ai créé un ticket dédié (#43 )

- ajouter une aide en ligne pour l'utilisateur (pas urgent)
- afficher le mode sélectionné (select, polygon ou freehand) dans le menu pour ne pas être perdu (urgent)
- dans la partie "cliché", écrire le nom de l'OPI sélectionnée avec la même couleur que celle qui lui correspond dans le graphe, pour savoir facilement (visuellement) quelle est l'image sélectionnée (urgent)
- ~~modifier le type/forme du curseur en fonction du mode sélectionné pour voir facilement le mode courant - on peut laisser celui par défaut (la flèche, celui qu'on a actuellement pour tous les modes) pour "select" et ajouter un curseur en forme de croix (crosshair), de préférence pas noir car pas bien visible, pour les saisies (urgent)~~
- ~~ajouter la possibilité d'interrompre une saisie en faisant "Echap" (urgent)~~
- ~~mettre l'opacité de l'OPI à une valeur plus grande (par exemple 0.5 au lieu de la valeur par défaut de 0.2), pour voir mieux l'OPI, son contenu et ses limites et faciliter ainsi les saisies~~
- ajouter un cadre sur les bords de l'OPI, pour voir facilement ses vraies limites pour saisie (zone utile + zone en dehors de celle-ci, contenant que des pixels noirs et pas affichée)

**Comment by amrosu** [comment]
- corriger ou enlever le mode "freehand" car pas fonctionnel

- bloquer les modes des saisies tant que "cliche" reste à "unknown" (les activer uniquement après sélection)

**Comment by amrosu** [comment]
- mettre l'opacité de l'OPI à une valeur plus grande (par exemple 0.5 au lieu de la valeur par défaut de 0.2), pour voir mieux l'OPI, son contenu et ses limites et faciliter ainsi les saisie

- ajouter un cadre sur les bords de l'OPI, pour voir facilement ses vraies limites pour saisie (zone utile + zone en dehors de celle-ci, contenant que des pixels noirs et pas affichée)
