### ISSUE TITLE
optimiser la structure du cache façon ROK4

### ISSUE THREAD

**Issue by ign-packo** [ign-packo/PackO#6]
# Objectifs

Il faut éviter d'avoir des millions de fichiers de qq Ko,
voir: https://github.com/rok4/rok4

En plus, il serait intéressant que le cache soit compatible avec les serveurs ROK4 (en tout cas pour la partie Ortho et Graphe). 

# Etapes

- il faut définir la notion de dalles (groupe de NxN tuiles)
- il faut utiliser un format Tiff compatible avec ROK4 (taille de l'entête et structure du fichier)
- il faut adopter la même hiérarchie de répertoire (basé sur les numéro de dalle en base 36)
- il faut générer les deux fichiers de métadonnées attendus par ROK4 (layer et pyramide)

Les modifs concernent la création du cache et le serveur (ça ne devrait pas avoir d'impact sur la partie iTowns).

**Comment by gmaillet** [comment]
à discuter après la formation ROK4 du 4 nov

**Comment by gmaillet** [comment]
J'ai commencé dans une branche rok4 avec un bout de code pour extraire et modifier des tuiles dans le format Tiff de ROK4 (un fichier test-rok4.js). Mais pour pouvoir démarrer des tests il va falloir préparer un cache façon ROK4.
J'ai l'impression que le plus simple, dans un premier temps, ça serait de faire un cache en changeant la taille des tuiles (pour en faire des dalles) et les dossiers de sortie. Puis d'utiliser l'un des outils de ROK4 (work2cache) pour encoder correctement nos dalles.

**Comment by amrosu** [comment]
devient obsolète
