### ISSUE TITLE
affichage niveaux dezoom

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#61]
Dans l'interface itowns, prévoir une méthode simple (ex: sous forme de boutons radio car un à la fois) pour l'affichage à différents niveaux de dezoom 8, 4, 2,1.

**Comment by amrosu** [comment]
ou encore plus instinctif, en utilisant la molette : un coup de molette = un dezoom

**Comment by gmaillet** [comment]
En priorité: 
- plus de zoom continue: on n'autorise que des niveaux 1, 1/2, 1/4, 1/8, 1/16, ...
- on l'affiche explicitement au niveau de l'échelle.

**Comment by gmaillet** [comment]
Cette Issue dépend de l'ajout de la caméra Ortho dans iTowns (en cours)

**Comment by ftoromanoff** [comment]
> En priorité:
> 
> * plus de zoom continue: on n'autorise que des niveaux 1, 1/2, 1/4, 1/8, 1/16, ...
> * on l'affiche explicitement au niveau de l'échelle.

Fait dans le PR #101
