### ISSUE TITLE
bug undo/redo - perte saisie

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#73]
En faisant des tests sur #67 et #65 (il est fort probable qu'il ne se trouve pas uniquement sur ces branches), j'ai trouvé ce bug : je fais une saisie (saisie1), ensuite un "undo", je fais une autre saisie (saisie2) dans la même zone que précédemment et ensuite un "redo" et au lieu d'avoir saisie1 qui apparait, j'ai le message : "nothing to redo"

**Comment by gmaillet** [comment]
Ce n'est pas un bug, mais le comportement que nous avions choisi: dès qu'une nouvelle saisie est faite on n'autorise plus les redo parce qu'ils pourraient être incohérents avec le nouvel état du cache.

**Comment by gmaillet** [comment]
Pris en compte dans #76
