### ISSUE TITLE
Compatibilité ROK4

### ISSUE THREAD

**Issue by gmaillet** [ign-packo/PackO#81]
Si on veut que notre cache soit totalement compatible avec ROK4 (pour l'ortho et le graphe), il faut:

- [x]  utiliser leur arborescence (chemin en base 36)
- [ ] utiliser leur structure de fichier (Tiff spéciaux) - branche spécifique ROK4 
- [ ] ajouter leurs MTD (un fichier qui décrit le layer et un fichier qui décrit la pyramide) pour chaque couche

Mais on a un problème plus profond: dans ROK4 les images associés aux layers sont stockés dans des arborescences séparées et sans suffixe. Du coup, on a trois options:

**1. on change notre structure pour avoir une arborescence séparée pour le graphe et l'ortho, mais ça n'est pas très pratique de ne pas avoir toutes les données de la dalle dans un même dossier.** - option choisie
2. on garde notre structure mais on ajoute des liens symboliques dans une structure avec des arborescences séparées pour être compatible ROK4 à tout moment sans recopie de donnée
3. on abandonne la compatibilité ROK4 en continue, mais on ajoute un script pour exporter notre cache dans la structure ROK4.

**Comment by amrosu** [comment]
Mais on a un problème plus profond: dans ROK4 les images associés aux layers sont stockés dans des arborescences séparées et sans suffixe. Du coup, on a trois options:
> 
>     1. on change notre structure pour avoir une arborescence séparée pour le graphe et l'ortho, mais ça n'est pas très pratique de ne pas avoir toutes les données de la dalle dans un même dossier.

Je pense qu'il serait intéressant d'aller jusqu'au bout de l'expérimentation, si cela ne nécessite pas trop de temps, pour avoir des éléments factuels pour décider si on applique ou rejete cette méthode

>     2. on garde notre structure mais on ajoute des liens symboliques dans une structure avec des arborescences séparées pour être compatible ROK4 à tout moment sans recopie de donnée

Utiliser des liens symboliques me paraît bien, mais assez fragile et il n'est pas sûr que ça marche sur windows

>     3. on abandonne la compatibilité ROK4 en continue, mais on ajoute un script pour exporter notre cache dans la structure ROK4.

C'est peut-être la méthode la plus simple, mais assurer la compatibilité a posteriori peut s'avérer compliqué / dangereux ; en plus, cela impliquerait d'avoir un "double" cache (un format "perso" et un format ROK4), au moins le temps de faire la transfo, et faire des tests que les deux contiennent les mêmes informations (pas de perte dans la transfo ou pendant)...

**Comment by gmaillet** [comment]
J'ai effectivement modifié la structure du cache pour être conforme à ROK4 (option 1) dans #80
