### ISSUE TITLE
Incohérences de structure entre cache et cache_test

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#84]
Dans overviews.json, list_OPI est un tableau dans cache_test et un objet dans les caches générés.
Une des conséquences : GetCapabilities ne fonctionne pas sur les caches générés car il n'attend pas un objet. 

Il faut donc : 

- corriger GetCapabilities

- générer cache_test via le script à chaque fois que ce dernier est modifié ; d'ailleurs cela permettrait de tester le générateur du cache indirectement avec npm test, et donc répondre en partie à #83

**Comment by ftoromanoff** [comment]
J'ai corrigé le GetCapabilities et cache_test/overviews.js sur la branche #78

**Comment by ftoromanoff** [comment]
Tout a fait d'accord pour générer cache_test a chaque fois, mais pour cela il va falloir réussir à installer gdal. A mois que ce problème est déjà été resolu ?
