### ISSUE TITLE
éviter les zoom/dezoom infinis

### ISSUE THREAD

**Issue by amrosu** [ign-packo/PackO#94]
Actuellement on peut faire des zooms et dezooms à l'infini. 
Il faudrait mettre en place des limites dans les deux sens ; il faudrait au moins qu'il s'arrête avant la disparition totale de l'image dans les deux sens.

**Comment by ftoromanoff** [comment]
En lien avec l'issue #61 on peut limiter les zooms aux niveaux existants dans le cache.
Doit on limiter le zoom maximal à la résolution maximale ? (c'est à dire un pixel écran = 1 pixel image au level max)
